version: "3.3"
services:
  plausible:
    depends_on:
      - geoip
    environment:
      - GEOLITE2_COUNTRY_DB=/geoip/GeoLite2-Country.mmdb

  geoip:
    image: maxmindinc/geoipupdate
    environment:
      - GEOIPUPDATE_EDITION_IDS=GeoLite2-Country
      - GEOIPUPDATE_FREQUENCY=168 # update every 7 days
    env_file:
      geoip/geoip.conf
    volumes:
      - geoip:/usr/share/GeoIP

volumes:
  geoip:
    driver: local
