apiVersion: v1
kind: Service
metadata:
  name: plausible-smtp
  labels:
    app.kubernetes.io/name: smtp
    app.kubernetes.io/component: email
    app.kubernetes.io/part-of: plausible
spec:
  type: ClusterIP
  ports:
    - name: smtp
      port: 25
      targetPort: 25
      protocol: TCP
  selector:
    app.kubernetes.io/name: smtp
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: plausible
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plausible-smtp
  labels:
    app.kubernetes.io/name: smtp
    app.kubernetes.io/component: email
    app.kubernetes.io/part-of: plausible
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: smtp
      app.kubernetes.io/component: email
      app.kubernetes.io/part-of: plausible
  template:
    metadata:
      labels:
        app.kubernetes.io/name: smtp
        app.kubernetes.io/component: email
        app.kubernetes.io/part-of: plausible
    spec:
      restartPolicy: Always
      containers:
        - name: plausible-smtp
          image: bytemark/smtp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 25
          securityContext:
            allowPrivilegeEscalation: false
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
            requests:
              memory: 5Mi
              cpu: 100m
          readinessProbe:
            tcpSocket:
              port: 25
            initialDelaySeconds: 20
            failureThreshold: 6
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 25
            initialDelaySeconds: 30
            failureThreshold: 3
            periodSeconds: 10
